name: CW
on:
  schedule:
  - cron: '30 9 * * 1-5'
  - cron: '40 9 * * 1-5'
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: job_one
      if: github.event.schedule == '40 9 * * 1-5'
      run: |
        echo job_one
        bash shell/check_in -i 15013941946 -t
    - name: job_two
      if: github.event.schedule == '30 9 * * 1-5'
      run: |
        echo job_two
        bash shell/check_in -i 15013941946 -t
