name: CW
on:
  schedule:
  - cron: "15 13 * * 1-5"
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: class down 
      run: |
        timedatectl set-timezone Asia/Shanghai
        timedatectl
        echo class down
        bash shell/check_in -i 15013941946 -d 1
