name: CW
on:
  schedule:
  - cron: "26 11 * * 1-5"
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: class down 
      run: |
        echo class down
        bash shell/check_in -i 15013941946 -u 1
        bash shell/check_in -i 15013941946 -t
