name: CW
on:
  schedule:
  - cron: "59 8 * * 1-5"
  - cron: "5 9 * * 1-5"
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: job_one
      if: github.event.schedule == '55 8 * * 1-5'
      run: |
        echo job_one
    - name: job_two
      if: github.event.schedule == '5 9 * * 1-5'
      run: |
        echo job_two
