name: CW
on:
  schedule:
  - cron: "14 8 * * 1-5"
  - cron: "15 8 * * 1-5"
jobs:
  job_one:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check_in on work
      run: |
        echo job_one
        bash check_in -i 15013941946 -t
  job_two:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check_in on work
      run: |
        echo job_two
        bash check_in -i 15013941946 -t
