name: CW
on: [push]
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check_in on work
      run: 
        echo check work
        bash shell/check_in -i 15013941946 -t
