name: CW
on:
  schedule:
  - cron: '13 12 * * 1-5'
  - cron: '55 11 * * 1-5'
jobs:
  myJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: class down
      if: github.event.schedule == '13 12 * * 1-5'
      run: |
        timedatectl set-timezone Asia/Shanghai
        timedatectl
        echo class down
        bash shell/check_in -i 15013941946 -d 1
    - name: class show
      if: github.event.schedule == '55 11 * * 1-5'
      run: |
        echo class show
        bash shell/check_in -i 15013941946 -t
