name: CW
on:
  schedule:
  - cron: "30 4 * * 1-5"
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: check_in on work
      run: 
        bash shell/check_in -i 15013941946 -t
