name: PL
on:
  schedule:
  - cron: "20 2 * * 1-5"
jobs:
  plJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        useragent="Mozilla/5.0 (Linux; Android 5.0; SM-G900P Build/LRX21T) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36 MicroMessenger/6.0.0.54_r849063.501 NetType/WIFI"
        curl -A "$useragent" http://weixintest.aspirecn.com:8081/yddkService/AttendanceApplication/companies/2440894028447744/staffs/339580210030714880/location
    
