name: 4.ipw.cn
on:
  schedule:
  - cron: ''
jobs:
  caseJob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: |
        echo exec...
        curl 4.ipw.cn
        curl -V
        
